clusters:
- id: EB1045DE-5FEA-4A60-9455-3727E1C0FD1C
  name: "BeijingCluster"
  description: "北京集群"
  loadbalancer: ""
  mycats:
  - name: "dn1"
    description: "北京节点1"
    host:  "10.12.1.171"
    osuser: "mycat_jingfen"
    ospassword: "mycat_jingfen_password"
    dataport: "8066"
    manageport: "9066"
    configpath: "/home/mycat_jingfen/mycat/conf/"
    mycatuser:  "admin"
    mycatpassword: "123456"
  mysqls:
  - url:  "10.12.1.171:8888"
    user:  "root"
    password: "000000000"
  - url:  "10.12.1.171:8777"
    user:  "root"
    password: "000000000"
- id: 5B69E4E7-1E1D-41B6-993E-10BEDE540D4B
  name: "XianCluster"
  description: "西安集群"
  loadbalancer: ""
  mycats:
  - name: "dn1"
    description: "西安节点1"
    host:  "10.12.1.171"
    osuser: "mycat_jingfen"
    ospassword: "mycat_jingfen_password"
    dataport: "8066"
    manageport: "9066"
    configpath: "/home/mycat_jingfen/mycat/conf/"
    mycatuser:  "admin"
    mycatpassword: "123456"
  mysqls:
  - url:  "10.12.1.171:8888"
    user:  "root"
    password: "000000000"
  - url:  "10.12.1.171:8777"
    user:  "root"
    password: "000000000"